Repository RyanNewsom/Majority-Wins, pull requests merged in 2020-09, with the labels that each got.

#2 Added TravisCI & Netlify
  .travis.yml
  README.md
  package.json
  src/App.test.tsx
  src/components/MainComponent.tsx
  src/tests/integration/App.test.tsx
Labels: devops

#15 Removed href in favor of react router api
  src/components/NavBar.tsx
Labels: bug

#23 Enable a home page w/ no nav bar
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/components/HomeComponent.tsx
  src/components/MainComponent.tsx
  src/components/NavBar.tsx
  src/images/statue-of-liberty.png
  src/index.tsx
Labels: enhancement

#17 Capture votes (WIP)
  db.json
  src/actions/CaptureVotesActions.ts
  src/components/BallotComponent.tsx
  src/components/CaptureVotesComponent.tsx
  src/components/MainComponent.tsx
  src/containers/AppContainer.tsx
  src/containers/CaptureVotesContainer.tsx
  src/models/App.ts
  src/reducers/appReducer.ts
  src/styles/layout.css
Labels: enhancement

#26 fixed sorting, added more voters, and state fix
  db.json
  src/components/RegisteredVotersTableComponent.tsx
  src/reducers/appReducer.ts
Labels: bug

#25 Feat/header enhance
  public/index.html
  src/components/CaptureVotesComponent.tsx
  src/components/MainComponent.tsx
  src/components/NavBar.tsx
  src/components/RegisterVotersComponent.tsx
  src/images/logo.png
Labels: enhancement
